version: '3.8'
services:
  # frontend:
  #   build:
  #     context: ./frontend
  #   ports:
  #     - "5173:5173"
  #   links:
  #   - backend
  # backend:
  #   build:
  #     context: ./backend
  #   ports:
  #     - "8000:8000"
  #   links:
  #     - nextcaldb
  #   depends_on:
  #     jobstopdb:
  #       condition: service_healthy
  nextcaldb:
    image: mysql:5.7
    ports:
      - "3316:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nextcal
      MYSQL_USER: nextcal
      MYSQL_PASSWORD: password
    healthcheck:
      test: ["CMD", "mysqladmin", "--password=password", "--user=nextcal", "status"]
      interval: 15s
      timeout: 10s
      retries: 10